### PR TITLE
Upgrade to Unicode 12.1.0

### LINKED ISSUE #29: Unicode 12.1 Support
https://www.unicode.org/versions/Unicode12.1.0/
http://blog.unicode.org/2019/05/unicode-12-1-en.html
https://github.com/python/cpython/commit/3aca40d3cb4b9b6741cf3073d71fbfc682cab96d
https://github.com/python/cpython/pull/13214
https://bugs.python.org/issue36861

### PR DESCRIPTION
**Pull request by Harmon758**
Matches https://github.com/python/cpython/commit/6fec905de5c139017f36b212e54cac46959808fe (https://github.com/python/cpython/pull/12855, https://bugs.python.org/issue36642) and https://github.com/python/cpython/commit/3aca40d3cb4b9b6741cf3073d71fbfc682cab96d (https://github.com/python/cpython/pull/13214, https://bugs.python.org/issue36861)
Resolves #29

### CODE REVIEW

**Comment by anthrotype** [comment]
also please try to change the line 63 of appveyor.yml like this:

```diff
-   - "pip install --upgrade setuptools wheel virtualenv"
+   - "python -m pip install --upgrade setuptools wheel virtualenv"
```

**Comment by Harmon758** [comment]
Done. I updated multibuild to the latest commit on the devel branch, since that seems to be what was already being used.

**Comment by anthrotype** [comment]
looks good, thank you

**Comment by anthrotype** [comment]
python 3.4 on macOS is failing on travis. I suggest you just drop it. If multibuild doesn't support it anymore, so neither we will. It's too much hassle for an almost-no-longer-maintained python version, and one can always build from source if they care.

**Comment by Harmon758** [comment]
It seems the Travis CI job is failing because multibuild no longer supports Python 3.4: https://github.com/matthew-brett/multibuild/commit/52d30bee6c6cdb578dc328e82880c0c173fd6ba5. Should I drop Python 3.4 support, since [it reached its EOL in March](https://www.python.org/dev/peps/pep-0429/)?

**Pull request merged**
